### ISSUE TITLE
reverse from left to right the html page

### ISSUE THREAD

**Issue by LioraPevzner** [LioraPinkhasov/CatchUp#1]

**Comment by amiellib** [comment]
i looked and we need to add where needed 
dir=rtl
https://www.w3.org/International/questions/qa-html-dir#dirauto for more info

**Comment by LioraPevzner** [comment]
![prob](https://user-images.githubusercontent.com/50797734/79133390-9ecc5d00-7db4-11ea-8fb1-c8e685fda618.PNG)
thanks, i do this func, it works,
i have a problem with what i show in the pic + i cant put the fliker menu in right,
![prob2](https://user-images.githubusercontent.com/50797734/79133505-ce7b6500-7db4-11ea-87a7-076276c614b7.PNG)

i will work on it a little bit later, i hope to finish it soon and begin to make the ohter pages.
